HPset = [

    # {
    #     'EPOCHS':100,
    #     'infra_command' : 16,
    #     'batch_size' : 32,
    #     'delta' : 5*1e-1,
    # },
    # {
    #     'EPOCHS':200,
    #     'lvl1_command' : 13,
    #     'channel1_dim' : 7,
    #     'batch_size' :  128,
    #     'delta' : 5*1e-1,
    # },
    # {
    #     'EPOCHS' : 200,
    #     'STEP_PER_EPOCH' : 30,
    #     'flow_depth' : 4,
    #     'flow_width' : 64,
    #     # 'DATASET' : 'MNIST',
    #     'DATASET' : 'FASHION',
    #     'channel1_width' : 32,
    #     'channel1_depth' : 2,
    #     'channel1_dim' : 8,
    #     'channel2_width' : 64,
    #     'channel2_depth' : 4,
    #     'channel2_sample' : 1,
    #     'channel2_dim' : 32,
    #     'batch_size' : 32,
    # },
    # {
    #     'EPOCHS' : 50,
    #     'STEP_PER_EPOCH' : 30,
    #     'flow_depth' : 3,
    #     'flow_width' : 64,
    #     # 'DATASET' : 'MNIST',
    #     'DATASET' : 'FASHION',
    #     'channel1_width' : 32,
    #     'channel1_depth' : 3,
    #     'channel1_dim' : 8z,
    #     'channel2_width' : 64,
    #     'channel2_depth' : 4,
    #     'channel2_sample' : 1,
    #     'channel2_dim' : 16,
    #     'batch_size' : 32,
    # },
    {
        'EPOCHS' :100,
        'STEP_PER_EPOCH' : 100,
        'flow_depth' : 3,
        'flow_width' : 8,
        'DATASET' : 'MNIST',
        'channel1_width' : 16,
        'channel1_depth' : 3,
        'channel1_dim' : 2,
        'channel2_width' : 256,
        'channel2_depth' : 2,
        'channel2_sample' : 1,
        'channel2_dim' : 2,
        'batch_size' : 32,
        'LR':1e-3,
    },

    # {
    #     'EPOCHS' :100,
    #     'STEP_PER_EPOCH' : 100,
    #     'flow_depth' : 4,
    #     'flow_width' : 48,
    #     'DATASET' : 'MNIST',
    #     'channel1_width' : 48,
    #     'channel1_depth' : 4,
    #     'channel1_dim' : 8,
    #     'channel2_width' : 1024,
    #     'channel2_depth' : 3,
    #     'channel2_sample' : 1,
    #     'channel2_dim' : 8,
    #     'batch_size' : 96,
    #     'LR':1e-3,
    # },
    # {
    #     'EPOCHS' :100,
    #     'STEP_PER_EPOCH' : 100,
    #     'flow_depth' : 4,
    #     'flow_width' : 48,
    #     'DATASET' : 'MNIST',
    #     'channel1_width' : 48,
    #     'channel1_depth' : 4,
    #     'channel1_dim' : 4,
    #     'channel2_width' : 1024,
    #     'channel2_depth' : 3,
    #     'channel2_sample' : 1,
    #     'channel2_dim' : 16,
    #     'batch_size' : 96,
    #     'LR':1e-3,
    # },
    # {
    #     'EPOCHS': 100,
    #     'STEP_PER_EPOCH': 100,
    #     'flow_depth': 4,
    #     'flow_width': 48,
    #     'DATASET': 'MNIST',
    #     'channel1_width': 48,
    #     'channel1_depth': 4,
    #     'channel1_dim': 4,
    #     'channel2_width': 1024,
    #     'channel2_depth': 3,
    #     'channel2_sample': 2,
    #     'channel2_dim': 16,
    #     'batch_size': 96,
    #     'LR': 1e-3,
    # },

    # {
    #     'EPOCHS' :500,
    #     'STEP_PER_EPOCH' : 30,
    #     'flow_depth' : 3,
    #     'flow_width' : 32,
    #     'DATASET' : 'CELEBa_GRAY_ONE',
    #     'channel1_width' : 16,
    #     'channel1_depth' : 4,
    #     'channel1_dim' : 16,
    #     'channel2_width' : 1,
    #     'channel2_depth' : 1,
    #     'channel2_sample' : 1,
    #     'channel2_dim' : 1,
    #     'batch_size' : 1,
    #     'LR':1e-2,
    # }
]
